### ISSUE TITLE
A little request

### ISSUE THREAD

**Issue by rigbyguapo** [UnitedRPMs/issues#32]
Hi, I do the petition to include Apache OpenOffice in the United RPMs repo, LibreOffice have some issues that make it a headache sometimes:

- Impress don't have workspace tabs, search normal and outline views in the bars is a lost of time.
- Impress don't have option Insert > File, (.txt need in my case)
- Writter have an bad direct cursor

There are other issues, I'm new in Linux world and can't configure the RPM's packages once installed, always have crashes in some time.

Thanks to this repo, Fedora already is one of the best distros.

Thanks, Regards.

**Comment by kuboosoft** [comment]
@rigbyguapo None distribution maintains openoffice.. and we don't have people who maintains openoffice; you can't install openoffice with libreoffice; because you will broke esentials parts in Gnome. Solutions, personallize with your hands...

![change](https://user-images.githubusercontent.com/4504351/58154377-b778d500-7c2e-11e9-8792-f669be55ddb1.png)

**Comment by rigbyguapo** [comment]
Hi kuboosoft, the KDE Scientific lab don't have libreoffice installed by default, I tryed the install in openSUSE after _zypper remove libreoffice_, openoffice (in openSUSE) works almost fine, only a little crash with impress, hope Linux don't destroys Apache Open Office compatibilite totaly in future, LibreOffice go so fast that forget little utilities that make life easy.

Many thanks for your work, your repo give an "ultraextra" to Fedora and makes a big difference.
